# Generated by Django 5.0.6 on 2024-09-19 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
