# Generated by Django 5.0.6 on 2024-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
