# Generated by Django 5.0.6 on 2024-09-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('percent', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_id', to='api.coupon')),
                ('product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sold_product', to='api.product')),
            ],
        ),
    ]
