# Generated by Django 5.0.6 on 2024-09-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coupon_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='coupon_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_id', to='api.coupon'),
        ),
    ]
